### ISSUE TITLE
Theme doesn't work with normal pages

### ISSUE THREAD

**Issue by nicdford** [webmandesign/playground-for-beaver-themer#1]
It would be awesome if this theme supported plain old vanilla beaver builder pages.

**Comment by webmandesign** [comment]
Hi @nicdford,

Great catch! Thank you for spotting this and sorry I haven't realized the issue before.

I've just released a theme update 1.0.1 fixing this issue. Please update the theme and enjoy :)

Regards,

Oliver

**Comment by nicdford** [comment]
HI @webmandesign this is a great solution! Thank you for getting it in so quickly.
